name: Build

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Release version tag name'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build web
        run: |
          cd web
          yarn install
          yarn export

      - name: init server build
        run: |
          sudo apt-get install gcc-mingw-w64
          mkdir -p build

      - name: Build windows amd64
        run: GOOS=windows GOARCH=amd64 CGO_ENABLED=1\
          CXX=x86_64-w64-mingw32-g++ CC=x86_64-w64-mingw32-gcc\
          go build -o build/control-panel-windows-amd64.exe ./api

      - name: Build linux amd64
        run: go build -o build/control-panel-linux-amd64 ./api

      - name: Build darwin amd64
        run: GOOS=darwin GOARCH=amd64 CGO_ENABLED=1\
          go build -o build/control-panel-darwin-amd64 ./api

      - name: upload Release
        uses: ncipollo/release-action@v1
        if: ${{ inputs.tagName }}
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tagName }}
          artifacts: './build/*'

      - name: upload Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'latest'
          artifacts: './build/*'
          replacesArtifacts: true
